# Python and SQL connction establishment

### import libraries and make connection

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
import statsmodels.api as sm

import warnings
warnings.filterwarnings('ignore')

In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\user\anaconda3\lib\site-packages (26.7.0)

In [3]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Sqldata@9797",
    database="black_friday_db"
)

if connection.is_connected():
    print("Connected successfully to black_friday_db!")

Connected successfully to black_friday_db!

In [6]:
cursor = connection.cursor()

cursor.execute("SELECT DATABASE()")

result = cursor.fetchone()

print("Connected Database:", result[0])

Connected Database: black_friday_db

In [7]:
query = """select * from black_friday_data"""
df = pd.read_sql(query,connection)
df.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00000142,F,0-17,10,A,2,0,3,4,5,13650
1,1000001,P00004842,F,0-17,10,A,2,0,3,4,12,13645
2,1000001,P00025442,F,0-17,10,A,2,0,1,2,9,15416
3,1000001,P00051442,F,0-17,10,A,2,0,8,17,Unknown,9938
4,1000001,P00051842,F,0-17,10,A,2,0,4,8,Unknown,2849

In [8]:
df.tail()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
550063,1006040,P00331042,M,26-35,6,B,2,0,5,8,Unknown,7058
550064,1006040,P00331942,M,26-35,6,B,2,0,5,Unknown,Unknown,3581
550065,1006040,P00343042,M,26-35,6,B,2,0,5,18,Unknown,6915
550066,1006040,P00346242,M,26-35,6,B,2,0,1,15,Unknown,15358
550067,1006040,P00349442,M,26-35,6,B,2,0,6,8,Unknown,16389

In [10]:
df.shape

(550068, 12)

In [11]:
df["User_ID"].nunique()

5891

In [12]:
df["Product_ID"].nunique()

3631

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     550068 non-null  int64
 1   Product_ID                  550068 non-null  object
 2   Gender                      550068 non-null  object
 3   Age                         550068 non-null  object
 4   Occupation                  550068 non-null  int64
 5   City_Category               550068 non-null  object
 6   Stay_In_Current_City_Years  550068 non-null  object
 7   Marital_Status              550068 non-null  int64
 8   Product_Category_1          550068 non-null  int64
 9   Product_Category_2          550068 non-null  object
 10  Product_Category_3          550068 non-null  object
 11  Purchase                    550068 non-null  int64
dtypes: int64(5), object(7)
memory usage: 50.4+ MB

In [14]:
df.dtypes

User_ID                        int64
Product_ID                    object
Gender                        object
Age                           object
Occupation                     int64
City_Category                 object
Stay_In_Current_City_Years    object
Marital_Status                 int64
Product_Category_1             int64
Product_Category_2            object
Product_Category_3            object
Purchase                       int64
dtype: object

In [15]:
df.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.duplicated(
    subset=["User_ID", "Product_ID"]
).sum()

np.int64(0)

In [18]:
df["Purchase"].describe()

count    550068.000000
mean       9263.968713
std        5023.065394
min          12.000000
25%        5823.000000
50%        8047.000000
75%       12054.000000
max       23961.000000
Name: Purchase, dtype: float64

In [19]:
(df["Purchase"] <= 0).sum()

np.int64(0)